### ISSUE TITLE
No data recieved from subscribeSignal method.

### ISSUE THREAD

**Issue by yash1200** [canonical/dbus.dart#107]
With the help of `example/signal.dart`, I was able to write this function but still no value is being recieved from it.

```
var client = DBusClient.system();
var object = DBusRemoteObject(
  client,
  'org.freedesktop.UPower',
  DBusObjectPath('/org/freedesktop/UPower/devices/DisplayDevice'),
);
var stream = object.subscribeSignal('org.freedesktop.UPower.Device', 'State');
await for (var signal in stream) {
  var state = (signal.values[0] as DBusUint64).value;
  print('State is : $state!');
}
```

**Comment by robert-ancell** [comment]
Looking at the UPower D-Bus interface using [D-Feet](https://wiki.gnome.org/Apps/DFeet) shows it doesn't have a `State` signal, but instead a `State` property. The [documentation](https://upower.freedesktop.org/docs/Device.html) confirm this.

With the following code I can monitor state changes as I connect and disconnect the power on my laptop. Hope this helps!

```dart
var client = DBusClient.system();
var object = DBusRemoteObject(client, 'org.freedesktop.UPower', DBusObjectPath('/org/freedesktop/UPower/devices/DisplayDevice'));

var state = await object.getProperty('org.freedesktop.UPower.Device', 'State');
print ('state: ${state}');
var stream = object.subscribePropertiesChanged();
await for (var signal in stream) {
  var state = signal.changedProperties['State'];
  if (state != null) {
    print ('state: ${state}');
  }
}
```

**Comment by robert-ancell** [comment]
This might help! https://pub.dev/packages/upower

**Comment by yash1200** [comment]
That's great. Thank you for this plugin. I made a PR with the help of your code [here](https://github.com/flutter/plugins/pull/2994) . Thank you for your help :).

**Comment by robert-ancell** [comment]
@yash1200 see https://github.com/canonical/upower.dart/pull/3 for monitoring the state (see example/monitor-state.dart).

**Comment by yash1200** [comment]
That's great. Till when can we expect the stable release of these plugins ?

**Comment by robert-ancell** [comment]
> That's great. Till when can we expect the stable release of these plugins ?

I don't have a schedule for a stable release, but I'm looking at:
- If I'm happy with the API and I feel it's complete (I think we're very close to that).
- If the feedback from other developers (like you, thanks!) suggests there's not issues with the current API.
