### ISSUE TITLE
Changed behavior and workaround

### ISSUE THREAD

**Issue by Piero512** [canonical/dbus.dart#194]
Hi

Today I was writing some tests on my package that uses this package and I noticed some stuff has changed a little. 

In the past, I used to call a method that received no parameters and returned nothing (precisely, org.freedesktop.Avahi.ServiceBrowser.Start()) which in the past didn't throw an exception when calling this method on Avahi versions lesser than 0.8. 

I was wondering, that since that method was added to the Avahi D-Bus API with the express purpose of being backward-compatible with old versions of Avahi (Ubuntu 20.04 LTS currently ships version 0.7).**Is there a way I can get the old nothing happens behavior explicitly?**

Most of the interfacing code is autogenerated from Avahi xml file definitions, but I keep my own changes on those generated classes. 

```dart
/// Invokes org.freedesktop.Avahi.ServiceBrowser.Start()
  Future<void> callStart() async {
    var result = await callMethod('org.freedesktop.Avahi.ServiceBrowser', 'Start', []);
    if (result.signature != DBusSignature('')) {
      throw 'org.freedesktop.Avahi.ServiceBrowser.Start returned invalid values \${result.values}';
    }
  }
```

This on my tests throws the following exception
```
Expected: null
  Actual: DBusMethodResponseException:<org.freedesktop.DBus.Error.UnknownMethod: Method "Start" with signature "" on interface "org.freedesktop.Avahi.ServiceBrowser" doesn't exist
          >
Expected no exceptions. Check if the service exists on the platform or the code broke
```

In case you wanted to replicate this issue, the code that triggers I suspect is 
https://github.com/Piero512/bonsoir_linux_dbus/blob/main/lib/src/linux_dbus_bonsoir_discovery.dart#L61-L107

**Comment by robert-ancell** [comment]
There's a couple of solutions you could do:

1. Check the error returned from the call:
```dart
var result = await callMethod('org.freedesktop.Avahi.ServiceBrowser', 'Start', []);
if (result is DBusMethodErrorResponse && result.errorName == 'org.freedesktop.DBus.Error.UnknownMethod') {
  return;
}
if (result.signature != DBusSignature('')) {
  throw 'org.freedesktop.Avahi.ServiceBrowser.Start returned invalid values ${result.values}';
}
```

2. Simply ignore the return value (you can decide if you want to await for the response or not):
```dart
await callMethod('org.freedesktop.Avahi.ServiceBrowser', 'Start', []);
```

3. Send the method call with a flag to stop Avahi from generating a response (new in dbus.dart 0.3.0, the await is optional again, but internally it won't wait for any response):
```dart
await callMethod('org.freedesktop.Avahi.ServiceBrowser', 'Start', [], flags: {DBusMethodCallFlag.noReplyExpected});
```

In case 3, there is a [D-Bus annotation we don't yet support](https://github.com/canonical/dbus.dart/issues/198) which would mean you could put the annotation in your XML and avoid modifying the generated code.

Hope this helps!

**Comment by Piero512** [comment]
Thank you, I will check the return value to make sure it waits for Avahi to finish when using Server2 API.
