### ISSUE TITLE
_read isolate never ends, which makes it impossible to close the app

### ISSUE THREAD

**Issue by Wazzaps** [canonical/dbus.dart#2]
Attempting to close my app makes it freeze, and after a couple of seconds spits out:
```Attempt:11 waiting for isolate _read to check in
Attempt:12 waiting for isolate _read to check in
Attempt:13 waiting for isolate _read to check in
Attempt:14 waiting for isolate _read to check in
Attempt:15 waiting for isolate _read to check in
Attempt:16 waiting for isolate _read to check in
Attempt:17 waiting for isolate _read to check in
Attempt:18 waiting for isolate _read to check in
Attempt:19 waiting for isolate _read to check in
Attempt:20 waiting for isolate _read to check in
Attempt:21 waiting for isolate _read to check in
Attempt:22 waiting for isolate _read to check in
Attempt:23 waiting for isolate _read to check in
Attempt:24 waiting for isolate _read to check in
... (and so on)
```

Probably need to add a `dispose`/`close` method, or make it detect the app is exiting somehow
Also, it looks like it's waiting in the `read` method of `UnixDomainSocket`. Maybe closing the socket will make it exit.

**Comment by robert-ancell** [comment]
Dart now supports Unix Domain Sockets, which means we can remove these isolate hacks to read from them. The remaining piece is sending the credentials over the socket, which I am working on a patch.

If you have a patch to fix this, please make a PR, otherwise hopefully we can drop this code soon.

**Comment by robert-ancell** [comment]
WIP change to use standard Dart socket in https://github.com/CanonicalLtd/dbus_client.dart/pull/11

**Comment by robert-ancell** [comment]
This should now be fixed!
