### ISSUE TITLE
Timeout Exception on Bus Reply.

### ISSUE THREAD

**Issue by Piero512** [canonical/dbus.dart#244]
Hi

I've been recently bitten by an update in DBus, as now it seems that syncronous DBus calls receive a Timeout from the server, in about 5 seconds. 

The problem happens on Ubuntu 20.04 LTS, with a default install of flutter and dbus 0.5.x. This issue did not happen on dbus 0.3.x

I receive the following unexpected exception from the server: 

`
org.freedesktop.Avahi.TimeoutError: TimeoutReached
`

As I traced back into my code, this happens when calling the method org.freedesktop.Avahi.Server.ResolveService using the avahi service files.
The stack trace is the following: 

<pre>00:15 <font color="#4E9A06">+0</font>: external_api Able to create a discovery without D-Bus complaining    
Enabling workaround for V1 API with the 100ms wait behavior. Update your Avahi version to 0.8 or later if you want this warning to disappear.
00:17 <font color="#4E9A06">+3</font>: end-to-end Broadcast name and receive them on service enumeration    
Enabling workaround for V1 API with the 100ms wait behavior. Update your Avahi version to 0.8 or later if you want this warning to disappear.
Cached service received: AvahiServiceBrowserItemNew(path: &apos;DBusObjectPath(&apos;/Client57/ServiceBrowser1&apos;)&apos;,interface: &apos;2&apos;,protocol: &apos;AvahiProtocol.AVAHI_PROTO_INET6&apos;, name: &apos;ItemNew&apos;,type: &apos;_bonsoire2e._tcp&apos;,domain: &apos;local&apos;
DBG: AvahiServiceBrowserItemNew(path: &apos;DBusObjectPath(&apos;/Client57/ServiceBrowser1&apos;)&apos;,interface: &apos;2&apos;,protocol: &apos;AvahiProtocol.AVAHI_PROTO_INET6&apos;, name: &apos;ItemNew&apos;,type: &apos;_bonsoire2e._tcp&apos;,domain: &apos;local&apos;
Item added! AvahiServiceBrowserItemNew(path: &apos;DBusObjectPath(&apos;/Client57/ServiceBrowser1&apos;)&apos;,interface: &apos;2&apos;,protocol: &apos;AvahiProtocol.AVAHI_PROTO_INET6&apos;, name: &apos;ItemNew&apos;,type: &apos;_bonsoire2e._tcp&apos;,domain: &apos;local&apos;
DBG: AvahiServiceBrowserItemNew(path: &apos;DBusObjectPath(&apos;/Client57/ServiceBrowser1&apos;)&apos;,interface: &apos;2&apos;,protocol: &apos;AvahiProtocol.AVAHI_PROTO_INET6&apos;, name: &apos;ItemNew&apos;,type: &apos;_bonsoire2e._tcp&apos;,domain: &apos;local&apos;
Cached service received: AvahiServiceBrowserItemNew(path: &apos;DBusObjectPath(&apos;/Client57/ServiceBrowser1&apos;)&apos;,interface: &apos;2&apos;,protocol: &apos;AvahiProtocol.AVAHI_PROTO_INET&apos;, name: &apos;ItemNew&apos;,type: &apos;_bonsoire2e._tcp&apos;,domain: &apos;local&apos;
DBG: AvahiServiceBrowserItemNew(path: &apos;DBusObjectPath(&apos;/Client57/ServiceBrowser1&apos;)&apos;,interface: &apos;2&apos;,protocol: &apos;AvahiProtocol.AVAHI_PROTO_INET&apos;, name: &apos;ItemNew&apos;,type: &apos;_bonsoire2e._tcp&apos;,domain: &apos;local&apos;
Item added! AvahiServiceBrowserItemNew(path: &apos;DBusObjectPath(&apos;/Client57/ServiceBrowser1&apos;)&apos;,interface: &apos;2&apos;,protocol: &apos;AvahiProtocol.AVAHI_PROTO_INET&apos;, name: &apos;ItemNew&apos;,type: &apos;_bonsoire2e._tcp&apos;,domain: &apos;local&apos;
DBG: AvahiServiceBrowserItemNew(path: &apos;DBusObjectPath(&apos;/Client57/ServiceBrowser1&apos;)&apos;,interface: &apos;2&apos;,protocol: &apos;AvahiProtocol.AVAHI_PROTO_INET&apos;, name: &apos;ItemNew&apos;,type: &apos;_bonsoire2e._tcp&apos;,domain: &apos;local&apos;
Cached service received: AvahiServiceBrowserItemNew(path: &apos;DBusObjectPath(&apos;/Client57/ServiceBrowser1&apos;)&apos;,interface: &apos;1&apos;,protocol: &apos;AvahiProtocol.AVAHI_PROTO_INET&apos;, name: &apos;ItemNew&apos;,type: &apos;_bonsoire2e._tcp&apos;,domain: &apos;local&apos;
DBG: AvahiServiceBrowserItemNew(path: &apos;DBusObjectPath(&apos;/Client57/ServiceBrowser1&apos;)&apos;,interface: &apos;1&apos;,protocol: &apos;AvahiProtocol.AVAHI_PROTO_INET&apos;, name: &apos;ItemNew&apos;,type: &apos;_bonsoire2e._tcp&apos;,domain: &apos;local&apos;
Item added! AvahiServiceBrowserItemNew(path: &apos;DBusObjectPath(&apos;/Client57/ServiceBrowser1&apos;)&apos;,interface: &apos;1&apos;,protocol: &apos;AvahiProtocol.AVAHI_PROTO_INET&apos;, name: &apos;ItemNew&apos;,type: &apos;_bonsoire2e._tcp&apos;,domain: &apos;local&apos;
DBG: AvahiServiceBrowserItemNew(path: &apos;DBusObjectPath(&apos;/Client57/ServiceBrowser1&apos;)&apos;,interface: &apos;1&apos;,protocol: &apos;AvahiProtocol.AVAHI_PROTO_INET&apos;, name: &apos;ItemNew&apos;,type: &apos;_bonsoire2e._tcp&apos;,domain: &apos;local&apos;
00:22 <font color="#4E9A06">+3</font><font color="#CC0000"> -1</font>: end-to-end Broadcast name and receive them on service enumeration <font color="#CC0000"><b>[E]</b></font>
  org.freedesktop.Avahi.TimeoutError: Timeout reached
  package:dbus/src/dbus_client.dart 1067:7                                DBusClient._callMethod
  ===== asynchronous gap ===========================
  dart:async                                                              _asyncErrorWrapperHelper
  package:bonsoir_linux_dbus/src/linux_dbus_bonsoir_discovery.dart 49:13  LinuxDBusBonsoirDiscovery.ready.&lt;fn&gt;
  ===== asynchronous gap ===========================
  dart:async                                                              _StreamImpl.listen
  package:dbus/src/dbus_client.dart 126:31                                DBusSignalStream.listen
  package:bonsoir_linux_dbus/src/linux_dbus_bonsoir_discovery.dart 39:12  LinuxDBusBonsoirDiscovery.ready
  ===== asynchronous gap ===========================
  dart:async                                                              _asyncThenWrapperHelper
  test/bonsoir_linux_dbus_test.dart 70:48                                 main.&lt;fn&gt;.&lt;fn&gt;
  test/bonsoir_linux_dbus_test.dart 61:68                                 main.&lt;fn&gt;.&lt;fn&gt;
  
  org.freedesktop.Avahi.TimeoutError: Timeout reached
  package:dbus/src/dbus_client.dart 1067:7                                DBusClient._callMethod
  ===== asynchronous gap ===========================
  dart:async                                                              _asyncErrorWrapperHelper
  package:bonsoir_linux_dbus/src/linux_dbus_bonsoir_discovery.dart 84:7   LinuxDBusBonsoirDiscovery.start.&lt;fn&gt;
  package:bonsoir_linux_dbus/src/linux_dbus_bonsoir_discovery.dart 76:57  LinuxDBusBonsoirDiscovery.start.&lt;fn&gt;
  ===== asynchronous gap ===========================
  dart:async                                                              _ForwardingStream.listen
  package:bonsoir_linux_dbus/src/linux_dbus_bonsoir_discovery.dart 76:50  LinuxDBusBonsoirDiscovery.start
  test/bonsoir_linux_dbus_test.dart 121:50                                main.&lt;fn&gt;.&lt;fn&gt;
  ===== asynchronous gap ===========================
  dart:async                                                              _asyncThenWrapperHelper
  test/bonsoir_linux_dbus_test.dart                                       main.&lt;fn&gt;.&lt;fn&gt;
  
  org.freedesktop.Avahi.TimeoutError: Timeout reached
  package:dbus/src/dbus_client.dart 1067:7                                DBusClient._callMethod
  ===== asynchronous gap ===========================
  dart:async                                                              _asyncErrorWrapperHelper
  package:bonsoir_linux_dbus/src/linux_dbus_bonsoir_discovery.dart 49:13  LinuxDBusBonsoirDiscovery.ready.&lt;fn&gt;
  ===== asynchronous gap ===========================
  dart:async                                                              _StreamImpl.listen
  package:dbus/src/dbus_client.dart 126:31                                DBusSignalStream.listen
  package:bonsoir_linux_dbus/src/linux_dbus_bonsoir_discovery.dart 39:12  LinuxDBusBonsoirDiscovery.ready
  ===== asynchronous gap ===========================
  dart:async                                                              _asyncThenWrapperHelper
  test/bonsoir_linux_dbus_test.dart 70:48                                 main.&lt;fn&gt;.&lt;fn&gt;
  test/bonsoir_linux_dbus_test.dart 61:68                                 main.&lt;fn&gt;.&lt;fn&gt;
  
  org.freedesktop.Avahi.TimeoutError: Timeout reached
  package:dbus/src/dbus_client.dart 1067:7                                DBusClient._callMethod
  ===== asynchronous gap ===========================
  dart:async                                                              _asyncErrorWrapperHelper
  package:bonsoir_linux_dbus/src/linux_dbus_bonsoir_discovery.dart 84:7   LinuxDBusBonsoirDiscovery.start.&lt;fn&gt;
  package:bonsoir_linux_dbus/src/linux_dbus_bonsoir_discovery.dart 76:57  LinuxDBusBonsoirDiscovery.start.&lt;fn&gt;
  ===== asynchronous gap ===========================
  dart:async                                                              _ForwardingStream.listen
  package:bonsoir_linux_dbus/src/linux_dbus_bonsoir_discovery.dart 76:50  LinuxDBusBonsoirDiscovery.start
  test/bonsoir_linux_dbus_test.dart 121:50                                main.&lt;fn&gt;.&lt;fn&gt;
  ===== asynchronous gap ===========================
  dart:async                                                              _asyncThenWrapperHelper
  test/bonsoir_linux_dbus_test.dart                                       main.&lt;fn&gt;.&lt;fn&gt;
  
  org.freedesktop.Avahi.TimeoutError: Timeout reached
  package:dbus/src/dbus_client.dart 1067:7                                DBusClient._callMethod
  ===== asynchronous gap ===========================
  dart:async                                                              _asyncErrorWrapperHelper
  package:bonsoir_linux_dbus/src/linux_dbus_bonsoir_discovery.dart 49:13  LinuxDBusBonsoirDiscovery.ready.&lt;fn&gt;
  ===== asynchronous gap ===========================
  dart:async                                                              _StreamImpl.listen
  package:dbus/src/dbus_client.dart 126:31                                DBusSignalStream.listen
  package:bonsoir_linux_dbus/src/linux_dbus_bonsoir_discovery.dart 39:12  LinuxDBusBonsoirDiscovery.ready
  ===== asynchronous gap ===========================
  dart:async                                                              _asyncThenWrapperHelper
  test/bonsoir_linux_dbus_test.dart 70:48                                 main.&lt;fn&gt;.&lt;fn&gt;
  test/bonsoir_linux_dbus_test.dart 61:68                                 main.&lt;fn&gt;.&lt;fn&gt;
  
  org.freedesktop.Avahi.TimeoutError: Timeout reached
  package:dbus/src/dbus_client.dart 1067:7                                DBusClient._callMethod
  ===== asynchronous gap ===========================
  dart:async                                                              _asyncErrorWrapperHelper
  package:bonsoir_linux_dbus/src/linux_dbus_bonsoir_discovery.dart 84:7   LinuxDBusBonsoirDiscovery.start.&lt;fn&gt;
  package:bonsoir_linux_dbus/src/linux_dbus_bonsoir_discovery.dart 76:57  LinuxDBusBonsoirDiscovery.start.&lt;fn&gt;
  ===== asynchronous gap ===========================
  dart:async                                                              _ForwardingStream.listen
  package:bonsoir_linux_dbus/src/linux_dbus_bonsoir_discovery.dart 76:50  LinuxDBusBonsoirDiscovery.start
  test/bonsoir_linux_dbus_test.dart 121:50                                main.&lt;fn&gt;.&lt;fn&gt;
  ===== asynchronous gap ===========================
  dart:async                                                              _asyncThenWrapperHelper
  test/bonsoir_linux_dbus_test.dart                                       main.&lt;fn&gt;.&lt;fn&gt;
  
00:23 <font color="#4E9A06">+3</font><font color="#CC0000"> -1</font>: <font color="#CC0000">Some tests failed.</font></pre>

My test file and entire source code is public at https://github.com/Piero512/bonsoir_linux_dbus

It seems like DBus is missing a timeout parameter for the method call and now that it parses the error messages correctly, this happens.

**Comment by robert-ancell** [comment]
This is a weird one:
- The `org.freedesktop.Avahi.TimeoutError` is being sent by the Avahi daemon - so the timeout is occurring outside of dbus.dart.
- There is no D-Bus timeout parameter in the protocol. So there's been no change here between dbus 0.3 and 0.5. If you wanted a client side timeout, you would have to implement that yourself.
- Looking at your code, the method calls should be the same between 0.3 and 0.5.

Can you double check if rolling back to 0.3 fixes the issues?

**Comment by Piero512** [comment]
Ok. I've reverted my changes in a separate [branch](https://github.com/Piero512/bonsoir_linux_dbus/tree/breakage_dbus), and the test runs with the expected results. Maybe there's a way I can isolate two packages that replicate the issue?

**Comment by robert-ancell** [comment]
Can you make a small project that reproduces the issue and does nothing else?

**Comment by Piero512** [comment]
I'll try my best this weekend.

**Comment by Piero512** [comment]
I finally got around to it. I reduced the code to review by a lot in this repo. https://github.com/Piero512/broken_dbus

**Comment by robert-ancell** [comment]
Thanks @Piero512. I can confirm running that here gives `org.freedesktop.Avahi.TimeoutError: Timeout reached`

**Comment by robert-ancell** [comment]
I've tried https://github.com/Piero512/broken_dbus by using dbus 0.3.3 by changing the following in the pubspec.yaml and modifying the code to work with the older dbus API:
```yaml
dependencies: 
  dbus: ^0.3.3
```

I can confirm that exactly the same behaviour works in 0.3.3 (i.e. the timeout error is received), so this is not a bug in dbus.dart, and is indeed coming from the Avahi daemon.

It may be have been your were ignoring the error in older code, which [now generates an exception in dbus.dart 0.5](https://github.com/canonical/dbus.dart/pull/215). If that is the case, you should update your code to something like:

```dart
DBusMethodSuccessResponse result;
try {
  result = await server.callResolveService(...);
} on DBusMethodResponseException catch (e) {
  if (e.response.errorName == 'org.freedesktop.Avahi.TimeoutError') {
    // Handle this error
  } else {
    rethrow;
  }
}
```

**Comment by Piero512** [comment]
Thanks for the help diagnosing this issue. I think I might migrate to ServiceResolver since ignoring the exception doesn't work, neither does retrying, and it's weird that it also happened on dbus 0.3.3 but the services resolved nonetheless. 

Update: Moving to Service Resolver didn't solve the issue in dbus 0.5.1 😭
