### ISSUE TITLE
Attempts to load libc.so.6 on Windows

### ISSUE THREAD

**Issue by GrigK** [canonical/dbus.dart#255]
Unhandled exception:
Invalid argument(s): Failed to load dynamic library 'libc.so.6': 126
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      getuid (package:dbus/src/getuid_linux.dart:8:32)
#3      new DBusClient.session (package:dbus/src/dbus_client.dart:223:19)

:-/ ver 0.5.4

**Comment by robert-ancell** [comment]
@GrigK do you have a D-Bus server working on Windows? I can add the Windows auth changes required but I don't have a system to test them on.

**Comment by robert-ancell** [comment]
Should be hopefully fixed in dbus.dart 0.5.5. I confirmed from a VM that the FFI code gets the correct SID value, but not against a running D-Bus server.
