### ISSUE TITLE
Naming conflicts with NetworkManager's PropertiesChanged signals

### ISSUE THREAD

**Issue by jpnurmi** [canonical/dbus.dart#99]
NetworkManager has some annoying deprecated `PropertiesChanged` signals, which are causing naming conflicts with `DBusRemoteObject.subscribePropertiesChanged()`.

- org.freedesktop.NetworkManager.PropertiesChanged
- org.freedesktop.NetworkManager.AccessPoint.PropertiesChanged
- org.freedesktop.NetworkManager.Device.PropertiesChanged
- ...

For example:

```bash
$ dart-dbus generate-remote-object org.freedesktop.NetworkManager.xml
```
=>
```dart
  /// Subscribes to org.freedesktop.NetworkManager.PropertiesChanged
  Future<DBusSignalSubscription> subscribePropertiesChanged(void Function(Map<String, DBusValue> properties) callback) async {
    return await subscribeSignal('org.freedesktop.NetworkManager', 'PropertiesChanged', (values) {
      if (values.length == 1 && values[0].signature == DBusSignature('a{sv}')) {
        callback((values[0] as DBusDict).children.map((key, value) => MapEntry((key as DBusString).value, (value as DBusVariant).value)));
      }
    });
  }
```
=>
> 'OrgFreedesktopNetworkManager.subscribePropertiesChanged' ('Future<DBusSignalSubscription> Function(void Function(Map<String, DBusValue>))') isn't a valid override of 'DBusRemoteObject.subscribePropertiesChanged' ('Future<DBusSignalSubscription> Function(void Function(String, Map<String, DBusValue>, List<String>))').

**Comment by robert-ancell** [comment]
At the top of `dart-dbus.dart`: 
```
// FIXME(robert-ancell): Check for method name collisions
```

I was considering if we want to namespace each interface, but it feels like it might be overkill for most cases. So I think the pragmatic solution is to detect the few collisions that occur and add something to the names for those cases only.

**Comment by Piero512** [comment]
Hey, I am in the process of writing a dart based connection to Avahi's DBus interface, and since I am not very familiar with how DBus works exactly, is it okay if I edit the generated code and rename the collisions or would something change?

```dart
/// Signal data for org.freedesktop.Avahi.AddressResolver.Found.
class OrgFreedesktopDBusIntrospectableFound extends DBusSignal{
  int get interface => (values[0] as DBusInt32).value;
  int get protocol => (values[1] as DBusInt32).value;
  int get aprotocol => (values[2] as DBusInt32).value;
  String get address => (values[3] as DBusString).value;
  String get name => (values[4] as DBusString).value;
  int get flags => (values[5] as DBusUint32).value;

  OrgFreedesktopDBusIntrospectableFound(DBusSignal signal) : super(signal.sender, signal.path, signal.interface, signal.member, signal.values);
}
```
In this example, the interface name collides with the super class method.

**Comment by robert-ancell** [comment]
@Piero512 you can edit the generated code and change the names, this API is only used by your app, and the DBus code doesn't call them.

**Comment by robert-ancell** [comment]
This should be greatly improved in 0.1.2.

**Comment by wstrange** [comment]
I think I am running into this issue. I generated a dart file from the systemd1 xml interface. 

The generated code has an error:

```dart
class OrgFreedesktopDBusPeer extends DBusRemoteObject {
  /// Stream of org.freedesktop.DBus.Properties.PropertiesChanged signals.
  /// ERROR: Isn't a valid override: supertype is <DBusPropertiesChangedSignal>
  late final Stream<OrgFreedesktopDBusPeerPropertiesChanged> propertiesChanged;

...
```

**Comment by robert-ancell** [comment]
If your XML file is the same one as the one I found with an internet search it contains definitions for the standard interfaces. You should remove these, and we should probably detect this and ignore them in the generator. Please open a new issue for this if this is a problem.

**Comment by wstrange** [comment]
I generated the XML using the following Dart code:

```dart
 var client = DBusClient.system();
    var sysd = DBusRemoteObject(client,
        name: 'org.freedesktop.systemd1',
        path: DBusObjectPath('/org/freedesktop/systemd1'));

    var m = await sysd.introspect();

    var f = File('systemd.xml');
    f.writeAsStringSync('${m.toXml()}');


```

**Comment by robert-ancell** [comment]
@wstrange I've opened https://github.com/canonical/dbus.dart/issues/375 to handle that case.

**Comment by robert-ancell** [comment]
Note that the original issue here was different interfaces that used the same method names. The case I've opened the new issue for is standard interfaces being defined and dbus.dart generating code for them that is already provided.
